
export {default as Background} from './background.png'
export {default as IconTemp} from './icon_temperatur.png'
export {default as Logo} from './Logo IS.svg'
export {default as World} from './world-svgrepo-com.svg'
export {default as City} from './city-buildings-svgrepo-com.svg'
export {default as Phone} from './telephone-bill-svgrepo-com.svg'
export {default as Mail} from './email-8-svgrepo-com.svg'
export {default as Download} from './download-square-svgrepo-com.svg'
export {default as Linkedin} from './linkedin-svgrepo-com.svg'
export {default as Xing} from './xing-svgrepo-com.svg'
export {default as Foto} from './foto.png'
export {default as Weather} from './Weather.png'
export {default as LeafGrow} from './LeafGrow.png'
export {default as CatFacts} from './CatFacts.png'
export {default as CatFactsBackground} from './cat.png'
export {default as Elipce} from './Ellipse 6.png'
export {default as Rectangle} from './Rectangle.png'
export {default as AITCertificate} from './AIT.jpg'
export {default as CrashKurs} from './Teilnahmebescheinigung Crashkurs B1-B2.Irene Schneider_page-0001.jpg'
export {default as Diplom} from './ZAB Anerkennung Schneider Irene_page-0001.jpg'
export {default as B1} from './TELC B1.jpg'
export {default as Udemy} from './Java сертификат2_page-0001.jpg'
export {default as Java1} from './Java1.jpg'
export {default as Spring} from './Spring.jpg'
export {default as SQL} from './SQL.jpg'
export {default as Skip} from './next-arrows-svgrepo-com.svg'
export {default as Joke} from './joke.jpg'
export {default as JokeTransporant} from './joke-transporant.png'
export {default as Insult} from './insult.jpg'


